sudo: false

addons:
  sources:
    - avsm
  apt:
    packages:
    - ocaml
    - opam

install:
- opam init -n
- eval `opam config env`
- opam install oasis -y
- opam install sedlex -y
- opam install menhir -y
- opam install js_of_ocaml -y
- oasis setup
- sh configure --enable-js

script:
- make build

after_success:
- bash deploy.sh