sudo: required

install:
- sudo add-apt-repository ppa:avsm/ppa -y
- sudo apt-get update
- sudo apt-get install -y ocaml
- sudo apt-get install -y opam
- opam init -n
- eval `opam config env`
- opam install oasis -y
- opam install sedlex -y
- opam install menhir -y
- opam install js_of_ocaml -y
- oasis setup
- sh configure --enable-js

script:
- make build

after_success:
- bash deploy.sh